### ISSUE TITLE
can you change button style?

### ISSUE THREAD

**Issue by zerod4y** [mIcHyAmRaNe/wso-webshell#2]
Hi
can you edit button style look like this
![image](https://user-images.githubusercontent.com/20386494/34903608-61f08100-f84a-11e7-847d-eb98b3e08e07.png)

**Comment by CyberTheReape** [comment]
@zerod4y yes... this is very nice....

**Comment by mIcHyAmRaNe** [comment]
will see that when i ll have free time

& something like this: good? 
![screenshot from 2019-02-14 00 28 54](https://user-images.githubusercontent.com/17873513/52751443-c167b800-2fef-11e9-9c30-f6f75d83e46b.png)

**Comment by CyberTheReape** [comment]
Yes nice..

**Comment by mIcHyAmRaNe** [comment]
i think that it's good like this 

<img src="https://raw.githubusercontent.com/mIcHyAmRaNe/wso-webshell/master/screenshots/wso-main.png"></img>
