### ISSUE TITLE
sql problem !

### ISSUE THREAD

**Issue by CyberTheReape** [mIcHyAmRaNe/wso-webshell#4]
hello. Thank you for this shell.
I'm using wso shell on metasploitable weak machine .  my weak machine has no mysql password ..I want to enter mysql database with wso shell but does not allow ..gives a warning like you have to enter the password ..there is no problem in an old wso-shell version. new problem with wso-shell versions ..

Can you fix this ?

**Comment by mIcHyAmRaNe** [comment]
try removing `required` in the line [1447](https://github.com/mIcHyAmRaNe/wso-webshell/blob/2a191fc399706823333b5f69e15a38113706b13c/wso.php#L1447) of the shell

**Comment by CyberTheReape** [comment]
@mlcHyAmRaNe    thank you.. it is working now
